"use client";

import { useState } from "react";
import { AlertTriangle, Download } from "lucide-react";
import type { SubtitleFormat, SubtitleReviewSummary } from "@/lib/subtitle-export/types";

type Props = { movieId: string; summary: SubtitleReviewSummary; filenames: Record<SubtitleFormat, string> };
export default function SubtitleExportControls({ movieId, summary, filenames }: Props) {
  const [format, setFormat] = useState<SubtitleFormat>("srt");
  const [mode, setMode] = useState("all");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const count = mode === "approved" ? summary.approved : summary.total;
  const hasNonApproved = summary.approved < summary.total;
  const controlClass = "w-full rounded-xl border border-white/10 bg-[#111114] px-3 py-3 text-sm text-zinc-200 focus-visible:outline-2 focus-visible:outline-white disabled:opacity-40";

  async function download() {
    setBusy(true); setError(""); setMessage("");
    try {
      const response = await fetch(`/api/movies/${encodeURIComponent(movieId)}/export/subtitles?format=${format}&mode=${mode}`, { cache: "no-store" });
      if (!response.ok) {
        const body = await response.json();
        throw new Error(body.error?.message ?? "Unable to export subtitles");
      }
      const filenameParameter = response.headers.get("Content-Disposition")?.match(/filename\*=UTF-8''([^;]+)/i)?.[1];
      const filename = filenameParameter ? decodeURIComponent(filenameParameter) : filenames[format];
      // Download server-generated bytes; this client never formats or rewrites subtitles.
      const url = URL.createObjectURL(await response.blob());
      const link = document.createElement("a");
      link.href = url; link.download = filename;
      document.body.appendChild(link); link.click(); link.remove();
      setTimeout(() => URL.revokeObjectURL(url), 30_000);
      setMessage(`${filename} prepared for download.`);
    } catch (failure) {
      setError(failure instanceof Error ? failure.message : "Download failed; please try again");
    } finally { setBusy(false); }
  }

  return <section className="min-w-0 space-y-5 rounded-2xl border border-white/10 bg-white/[0.025] p-5 sm:p-6" aria-labelledby="subtitle-download-title">
    <div><h2 id="subtitle-download-title" className="text-sm font-medium">Download subtitles</h2><p className="mt-2 text-xs leading-5 text-zinc-500">Current saved Myanmar text, including human edits. Timing remains unchanged.</p></div>
    <div className="grid gap-4 sm:grid-cols-2">
      <label htmlFor="export-format" className="space-y-2 text-xs text-zinc-400"><span className="block">Format</span><select id="export-format" value={format} disabled={busy} className={controlClass} onChange={(event) => { setFormat(event.target.value as SubtitleFormat); setError(""); setMessage(""); }}><option value="srt">SRT</option><option value="ass">ASS</option></select></label>
      <label htmlFor="export-mode" className="space-y-2 text-xs text-zinc-400"><span className="block">Review filter</span><select id="export-mode" value={mode} disabled={busy} className={controlClass} onChange={(event) => { setMode(event.target.value); setError(""); setMessage(""); }}><option value="all">All current subtitles</option><option value="approved">Approved only</option></select></label>
    </div>
    {hasNonApproved && <p role="status" className="flex items-start gap-2 rounded-xl border border-amber-200/15 bg-amber-200/[0.025] p-3 text-sm leading-6 text-amber-100/80"><AlertTriangle size={16} className="mt-1 shrink-0" />{mode === "approved" ? "Approved-only export will omit unreviewed or needs-review subtitles. Original time gaps are preserved." : "This export includes subtitles that have not been approved."}</p>}
    {mode === "approved" && !summary.approved && <p className="text-sm text-zinc-400">No approved subtitles yet. Approve rows in Translation before downloading this mode.</p>}
    {!summary.total && <p className="text-sm text-zinc-400">No current translated segments to export.</p>}
    <dl className="grid gap-4 text-sm sm:grid-cols-3">
      <div className="min-w-0 sm:col-span-2"><dt className="text-xs text-zinc-500">Filename</dt><dd className="mt-1 break-words text-zinc-200">{filenames[format]}</dd></div>
      <div><dt className="text-xs text-zinc-500">Selected segments</dt><dd className="mt-1 text-zinc-200">{count} of {summary.total}</dd></div>
    </dl>
    <p className="text-xs leading-5 text-zinc-500">UTF-8 · {format === "srt" ? "Millisecond timing, plain subtitle layout." : "Centisecond timing, bottom-centered text with installed sans-serif font fallback."} Downloads use the current saved translation; review counts reflect this page load.</p>
    <button type="button" onClick={() => void download()} disabled={busy || !count} className="inline-flex max-w-full items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black hover:bg-zinc-200 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white disabled:opacity-40"><Download size={16} />{busy ? "Preparing download…" : `Download ${format.toUpperCase()}`}</button>
    <div aria-live="polite">{message && <p role="status" className="break-words text-sm text-zinc-300">{message}</p>}{error && <p role="alert" className="text-sm text-amber-200">{error}</p>}</div>
  </section>;
}
